apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: kibana
        image: docker.io/elastic/kibana:7.17.3
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-master:9200"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              http () {
                curl -XGET -s -k --fail http://127.0.0.1:5601${1}
              }
              # Accepter yellow ou green pour Kibana
              http "/api/status" | grep -q '"level":"available"'
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
