apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic
spec:
  replicas: 1
  selector:          # ⚠️ OBLIGATOIRE !
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:        # ⚠️ Doit correspondre au selector !
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.io/elastic/kibana:7.17.3
        ports:
        - containerPort: 5601
          name: http
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-master:9200"
        - name: SERVER_HOST
          value: "0.0.0.0"
        readinessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 30
          periodSeconds: 10
